### ISSUE TITLE
Use cases are also a type of document

### ISSUE THREAD

**Issue by rduerr** [earthcubearchitecture-ecresourcereg/ecrro#13]
Please update the Resource diagram to include use cases, glossaries, ontologies, and vocabularies as types of documents.

**Comment by smrgeoinfo** [comment]
I'd say that the glossary, ontology, vocabulary, use case is a resource like an FRBR Work, and the document is a representation of that work.  I've been wrestling with this problem since asserting that a specification is a document, but now think its better to think of a specification as the set of rules, recommendations, validation tests etc that are the information content of the spec, and a spec document is just one possible representation (but of course the most likely...)

**Comment by rduerr** [comment]
Well in that case, I’d rather use the schema term DefinedTermSet which could cover all of them except use case under the creative work category.

**Comment by rduerr** [comment]
Also, I note that I am taking silence on topics as consent… [hint, hint, hint, re emails from the past few days)

**Comment by rduerr** [comment]
Discussion OBE - closing
