### ISSUE TITLE
Why is foaf:Person a subclass of spatial thing?

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcubearchitecture-ecresourcereg/ecrro#32]
http://xmlns.com/foaf/0.1/Person ofwl:subclassof http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing

why???

**Comment by rduerr** [comment]
Because the file http://xmlns.com/foaf/spec/index.rdf (i.e., the spec) asserts that it is so.  I hadn't noticed that until you called it out; but it certainly does explain some of the odd DCAT and other errors related to FOAF!  I suggest you move this issue over to whatever issue list the FOAF folks maintain.

**Comment by smrgeoinfo** [comment]
http://lists.foaf-project.org/pipermail/foaf-dev/ looks pretty moribund and I don't see any other issue tracker.  I suspect they're not very interested in thinking about such an issue. We just need to be aware of this in case it causes any problems in our work.
